# Generated by Django 3.0.5 on 2020-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apellido', models.CharField(max_length=25)),
                ('Nombres', models.CharField(max_length=25)),
                ('Cedula', models.CharField(max_length=14)),
                ('FechaNacimiento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Prestamos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=3)),
                ('plazo', models.CharField(max_length=25)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
