# Generated by Django 3.0.5 on 2020-09-11 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fempleados', '0002_departamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='Estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='prestamos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
