# Generated by Django 3.0.5 on 2020-09-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piezas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Descripcion', models.CharField(max_length=25)),
                ('Tipo', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=25)),
                ('Credito', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Suministra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=3)),
                ('Pieza_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpiezas.Piezas')),
                ('Proveedor_cod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fpiezas.Proveedor')),
            ],
        ),
    ]
