# Generated by Django 3.0.5 on 2020-09-08 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriculas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Estudiante', models.CharField(max_length=25)),
                ('Carrera', models.CharField(max_length=25)),
                ('Semestre', models.CharField(max_length=14)),
                ('Fecha', models.DateField()),
                ('Costo', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
