# Generated by Django 3.0.5 on 2020-09-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculas',
            name='Costo',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
