# Generated by Django 3.0.5 on 2020-10-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matriculas', '0002_auto_20200908_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculas',
            name='NotaSemAnt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matriculas',
            name='Paralelo',
            field=models.CharField(default='A', max_length=5),
        ),
    ]
